### PR TITLE
Fix filtering of variables in update query

### LINKED ISSUE #6549: entity out of scope in insert statement following a delete statement.
## Description

I'm trying to execute a query resulting in an error.

## Environment

1. OS (where TypeDB server runs): Archlinux
2. TypeDB version (and platform): 2.8.1
3. TypeDB client: console
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Define
schema:

define
name sub attribute,
 value string;

attr1 sub attribute,
 value string;

entity1 sub entity,
owns name,
owns attr1,
plays relation1:role1;

entity2 sub entity,
owns name,
owns attr1,
plays relation1:role2;

relation1 sub relation,
relates role1,
relates role2;

2. Run

insert $x isa entity1, has name "name1", has attr1 "attr1";

3. Run

match $s isa entity1, has name "name1";
$s has attr1 $old_attr; $old_attr "attr1";
delete $s has $old_attr;
insert $out_of_scope isa entity2, has name "name2";
(role1:$s, role2:$out_of_scope) isa relation1;

4. Run (missing delete statement) this works for me

match $s isa entity1, has name "name1";
$s has attr1 $old_attr; $old_attr "attr1";
insert $out_of_scope isa entity2, has name "name2";
(role1:$s, role2:$out_of_scope) isa relation1;

5. Run (missing insert statement) this works for me

match $s isa entity1, has name "name1";
$s has attr1 $old_attr; $old_attr "attr1";
delete $s has $old_attr;

## Expected Output

Successful execution of the query

## Actual Output

com.vaticle.typeql.lang.common.exception.TypeQLException: [TQL16] TypeQL Error: The variable '$out_of_scope' is out of scope of the match query.

Please check server logs for the stack trace.
 
## Additional information

stack trace:
ERROR com.vaticle.typedb.core.server.TransactionService - com.vaticle.typeql.lang.common.exception.TypeQLException: [TQL16] TypeQL Error: The variable '$out_of_scope' is out of scope of the match query.
com.vaticle.typedb.core.common.exception.TypeDBException: com.vaticle.typeql.lang.common.exception.TypeQLException: [TQL16] TypeQL Error: The variable '$out_of_scope' is out of scope of the match query.
	at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:51)
	at com.vaticle.typedb.core.database.RocksStorage.exception(RocksStorage.java:174)
	at com.vaticle.typedb.core.database.RocksStorage$TransactionBounded.exception(RocksStorage.java:328)
	at com.vaticle.typedb.core.database.RocksStorage$Data.exception(RocksStorage.java:376)
	at com.vaticle.typedb.core.graph.GraphManager.exception(GraphManager.java:55)
	at com.vaticle.typedb.core.concept.ConceptManager.exception(ConceptManager.java:222)
	at com.vaticle.typedb.core.query.QueryManager.update(QueryManager.java:156)
	at com.vaticle.typedb.core.server.query.QueryService.update(QueryService.java:172)
	at com.vaticle.typedb.core.server.query.QueryService.execute(QueryService.java:102)
.....

### PR DESCRIPTION
**Pull request by shiladitya-mukherjee**
## What is the goal of this PR?

We fix the filtering of variables in insert clause of update queries to allow inserting new entities.

Fixes #6549 

## What are the changes implemented in this PR?

For the output of the `match` query that subsequently feeds into delete and insert, the filters of the `get` are the intersection of the `insert` and the `match` query, as well as the variables in the `delete`. Further, the set of variables in the `delete` query should be a subset of the set of variables in `match` query.

### CODE REVIEW

File: query/Updater.java [hunk 1]
```diff
@@ -71,8 +71,10 @@ public static Updater create(Reasoner reasoner, ConceptManager conceptMgr, TypeQ
             insertRegistry.variables().forEach(Inserter::validate);
 
             assert query.match().namedVariablesUnbound().containsAll(query.namedDeleteVariablesUnbound());
-            HashSet<UnboundVariable> filter = new HashSet<>(query.namedDeleteVariablesUnbound());
-            filter.addAll(query.namedInsertVariablesUnbound());
+
+            HashSet<UnboundVariable> filter = new HashSet<>(query.match().namedVariablesUnbound());
```
Comment (krishnangovindraj) [inline query/Updater.java:75]: Try not to add new lines if they're not needed (so they mean something when we use them where they are needed)

**Review by krishnangovindraj — CHANGES_REQUESTED** [review]
Please add the typedb repository to your factory settings so CI will run.

We can also restructure the PR description to be more concise. But overall, looks good :)

**Review by krishnangovindraj — APPROVED** [review]
Looks good to me.

**Review by benjaminasmall — APPROVED** [review]
@krishnangovindraj says good.

**Review by flyingsilverfin — APPROVED** [review]
