### PR TITLE
Fetch query can infer fetched attributes

### LINKED ISSUE #6952: Attribute fetch should trigger reasoning
## Description

Fetching attributes should trigger reasoning if there are rules to apply and return inferred ownerships, as well as stored ones.

## Environment

1. TypeDB distribution: All
2. TypeDB version: 2.25.x
3. Environment: All
4. Client and version: -
5. Other details: -

## Reproducible Steps

1. Set up
- define a schema with an inferred attribute ownership

2. Test/Query

Run a fetch query in a transaction with inference enabled 

3. Unexpected result

The inferred attributes will be absent.

## Expected result

Inferrable attribuet is present.

### PR DESCRIPTION
**Pull request by flyingsilverfin**
## Usage and product changes

We fix #6952 , by allowing attribute fetching to trigger reasoning. For example;

Given:
```
define
rule has-name: when { $x isa person; } then { $x has name "John"; };
```

Then the query:
```
match $x isa person;
fetch $x: name;
```

Can now retrieve `name "John"` as part of the fetch response.

### CODE REVIEW

File: concept/answer/ConceptMap.java [hunk 1]
```diff
@@ -48,14 +49,12 @@
 
 public class ConceptMap {
 
+    public static ConceptMap EMPTY = new ConceptMap(Collections.emptyMap());
```
Comment (flyingsilverfin) [inline concept/answer/ConceptMap.java:52]: This might improve performance a bit - ConceptMaps are immutable and so the empty constructor can just be re-used as a singleton

File: query/Fetcher.java [hunk 2]
```diff
@@ -259,15 +266,30 @@ ReadableConceptTree.Node.Map execute(Reasoner reasoner, ConceptManager conceptMg
...
-                attributeFetches.forEach(attrFetch -> entries.add(
-                        attrFetch.name(),
-                        new ReadableConceptTree.Node.List(
-                                thing.getHas(attrFetch.attributeTypes(), emptySet()).map(ReadableConceptTree.Node.Leaf::new).toList()
-                        )
-                ));
+                Identifier.Variable.Name attrVar = Identifier.Variable.namedConcept("attr");
+                attributeFetches.forEach(attrFetch -> {
+                    // use a new context to avoid taking limits into sub-query
+                    Context.Query subContext = new Context.Query(context.parent(), context.options());
```
Comment (flyingsilverfin) [inline query/Fetcher.java:272]: Bug fix: we should not pass the outer Context into the inner query, since it may contain a limit on the Producer context.

File: query/Fetcher.java [hunk 3]
```diff
@@ -259,15 +266,30 @@ ReadableConceptTree.Node.Map execute(Reasoner reasoner, ConceptManager conceptMg
...
+                    List<ReadableConceptTree.Node.Leaf<com.vaticle.typedb.core.concept.thing.Attribute>> c = reasoner.execute(createAttributeQuery(attrFetch.attributeType, attrVar, thing),
+                                    list(), TypeQLQuery.Modifiers.EMPTY, subContext, ConceptMap.EMPTY)
+                            .map(cm -> new ReadableConceptTree.Node.Leaf<>(cm.get(attrVar).asAttribute()))
+                            .toList();
+                    entries.add(attrFetch.name(), new ReadableConceptTree.Node.List(c));
+                });
                 return entries;
             }
 
+            private Disjunction createAttributeQuery(AttributeType attributeType, Identifier.Variable.Name attributeVariable, Thing attrOwner) {
```
Comment (flyingsilverfin) [inline query/Fetcher.java:282]: We now convert the attribute fetch into a reasoner query

File: query/Fetcher.java [hunk 4]
```diff
@@ -331,10 +358,11 @@ public static Projection create(Reasoner reasoner, ConceptManager conceptMgr, Co
                 )) {
                     throw TypeDBException.of(SUBQUERY_UNBOUNDED, key.label());
                 }
-
+                // use a new context to avoid taking limits into sub-query
+                Context.Query subContext = new Context.Query(context.parent(), context.options());
```
Comment (flyingsilverfin) [inline query/Fetcher.java:362]: Bug fix: same as before, we do not pass the outer query's context into the inner one, creating a new context from the transaction context directly.
