### PR TITLE
Fix TypeDB formula name for Homebrew

### LINKED ISSUE #6335: the command `brew tap vaticle/tap` leads to an error
## Description

the command `brew tap vaticle/tap` leads to an error

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform): TypeDB 2.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run `brew tap vaticle/tap`

## Expected Output

set up vaticle tap

## Actual Output

```
brew tap vaticle/tap
````
> ==> Tapping vaticle/tap
> Cloning into '/usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap'...
> remote: Enumerating objects: 307, done.
> remote: Counting objects: 100% (203/203), done.
> remote: Compressing objects: 100% (131/131), done.
> remote: Total 307 (delta 51), reused 182 (delta 31), pack-reused 104
> Receiving objects: 100% (307/307), 44.61 KiB | 1015.00 KiB/s, done.
> Resolving deltas: 100% (81/81), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap/Formula/typedb.rb
> No available formula with the name "typedb".
> In formula file: /usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap/Formula/typedb.rb
> Expected to find class Typedb, but only found: TypeDB.
> Error: Cannot tap vaticle/tap: invalid syntax in tap!

### PR DESCRIPTION
**Pull request by vmax**
## What is the goal of this PR?

Allow TypeDB to be installed via Homebrew through renaming the formula to adhere to Homebrew expectation.

## What are the changes implemented in this PR?

Fix #6335

Rename formula class to what Homebrew expects it to be (`Typedb`) and therefore make package installable again.

### CODE REVIEW

File: config/brew/typedb.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 
-class TypeDB < Formula
+class Typedb < Formula
```
Comment (vmax) [inline config/brew/typedb.rb:18]: With formula name that doesn't match Homebrew convention, users would not be able to install TypeDB and installation would fail with this error:

```
In formula file: /usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap/Formula/typedb.rb
Expected to find class Typedb, but only found: TypeDB.
```

Therefore, we're renaming the formula to what Homebrew expects.
