### PR TITLE
Throw exception when attribute value type is modified

### LINKED ISSUE #6789: Modifying an attribute value type neither throws exception nor has effects
## Description
Trying to redefine an attribute type as follows throw an exception as expected:

```typeql
define 
redefine-me sub attribute, value long;
define
redefine-me value string;

# Exception:
# [TYW15] Invalid Type Write: An attribute value type (in this case 'STRING') can only be set onto an attribute type (in this case 'redefine-me') when it was defined for the first time.
```

However, the following query does not:

```typeql
define 
redefine-me sub attribute, value long;
define
redefine-me sub attribute, value string;

# Success
```
## Environment

1. OS (where TypeDB server runs): macOS Ventura { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. TypeDB version (and platform): 2.16.1
3. TypeDB client: BDD/Studio
4. Other environment details:

## Reproducible Steps
As in the description

## Expected Output
The following error message
```
 [TYW15] Invalid Type Write: An attribute value type (in this case 'STRING') can only be set onto an attribute type (in this case 'redefine-me') when it was defined for the first time.
```
## Actual Output
Query succeeds and commits.

### PR DESCRIPTION
**Pull request by krishnangovindraj**
## What is the goal of this PR?
Throw an exception when a `define` query attempts to modify the an existing the attribute type with a different value type.

## What are the changes implemented in this PR?
* Throw an exception when a `define` query attempts to modify the redefine the attribute type with a different value type.

- fixes #6789

### CODE REVIEW

File: query/Definer.java [hunk 1]
```diff
@@ -195,6 +195,9 @@ private ThingType defineSub(ThingType thingType, SubConstraint subConstraint, Ty
                 else if (!supertype.isRoot()) valueType = supertype.asAttributeType().getValueType();
                 else throw TypeDBException.of(ATTRIBUTE_VALUE_TYPE_MISSING, labelConstraint.label());
                 if (thingType == null) thingType = conceptMgr.putAttributeType(labelConstraint.label(), valueType);
+                else if (supertype.isRoot() && !valueType.equals(thingType.asAttributeType().getValueType())) {
```
Comment (krishnangovindraj) [inline query/Definer.java:198]: If super type is not root, a more appropriate error is throw.

**Review by flyingsilverfin — APPROVED** [review]
